name: Test PyPI'ye Yayınlama

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Kodu Checkout Et
        uses: actions/checkout@v2

      - name: Python'u Kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Paketi Derle
        run: python -m build

      - name: Test PyPI'ye Yayınla
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
